Script started on Wed 13 May 2015 09:22:02 PM PDT
]0;lolipopping@debian: ~/Documents/rshelllolipopping@debian:~/Documents/rshell$ bin/rshell
lolipopping@debian$#input
lolipopping@debian$ls
bin  LICENSE  makefile	piping.script  README.md  src  testpipe  tests
lolipopping@debian$ls -a > test
lolipopping@debian$cat < test
.
..
bin
.git
.gitignore
LICENSE
makefile
piping.script
README.md
src
test
testpipe
tests
lolipopping@debian$cat < test2
open 1: No such file or directory
]0;lolipopping@debian: ~/Documents/rshelllolipopping@debian:~/Documents/rshell$ bin/rshell
lolipopping@debian$cat <     cat                          <                 test
.
..
bin
.git
.gitignore
LICENSE
makefile
piping.script
README.md
src
test
testpipe
tests
lolipopping@debian$             cat                <            tes t  t                  
.
..
bin
.git
.gitignore
LICENSE
makefile
piping.script
README.md
src
test
testpipe
tests
lolipopping@debian$cat<test
.
..
bin
.git
.gitignore
LICENSE
makefile
piping.script
README.md
src
test
testpipe
tests
lolipopping@debian$grep e<test
.gitignore
makefile
test
testpipe
tests
lolipopping@debian$ls -a | cat < test
.
..
bin
.git
.gitignore
LICENSE
makefile
piping.script
README.md
src
test
testpipe
tests
lolipopping@debian$cat < ts est | grep e
.gitignore
makefile
test
testpipe
tests
lolipopping@debian$#outtput
lolipopping@debian$ls -a > test
lolipopping@debian$cat < test
.
..
bin
.git
.gitignore
LICENSE
makefile
piping.script
README.md
src
test
testpipe
tests
lolipopping@debian$ls -a >> test2
lolipopping@debian$ls    cat < test2
.
..
bin
.git
.gitignore
LICENSE
makefile
piping.script
README.md
src
test
test2
testpipe
tests
lolipopping@debian$ls -a > test
lolipopping@debian$cat < test
.
..
bin
.git
.gitignore
LICENSE
makefile
piping.script
README.md
src
test
test2
testpipe
tests
lolipopping@debian$ls -a >> test
lolipopping@debian$cat < test
.
..
bin
.git
.gitignore
LICENSE
makefile
piping.script
README.md
src
test
test2
testpipe
tests
.
..
bin
.git
.gitignore
LICENSE
makefile
piping.script
README.md
src
test
test2
testpipe
tests
lolipopping@debian$ls -a < > test
lolipopping@debian$cat < test
.
..
bin
.git
.gitignore
LICENSE
makefile
piping.script
README.md
src
test
test2
testpipe
tests
lolipopping@debian$cat < test
.
..
bin
.git
.gitignore
LICENSE
makefile
piping.script
README.md
src
test
test2
testpipe
tests
lolipopping@debian$cat < test2
.
..
bin
.git
.gitignore
LICENSE
makefile
piping.script
README.md
src
test
test2
testpipe
tests
lolipopping@debian$ls -a > test2
lolipopping@debian$cat < test2
.
..
bin
.git
.gitignore
LICENSE
makefile
piping.script
README.md
src
test
test2
testpipe
tests
lolipopping@debian$ca  ls -a            >             test4
lolipopping@debian$            ls          -a         >          test  4
lolipopping@debian$cat M t   < test4
.
..
bin
.git
.gitignore
LICENSE
makefile
piping.script
README.md
src
test
test2
test4
testpipe
tests
lolipopping@debian$ls        > test5
lolipopping@debian$       ;s    ;s    ls            >>    test5         
lolipopping@debian$cat < test5
bin
LICENSE
makefile
piping.script
README.md
src
test
test2
test4
test5
testpipe
tests
bin
LICENSE
makefile
piping.script
README.md
src
test
test2
test4
test5
testpipe
tests
lolipopping@debian$cat<test4
.
..
bin
.git
.gitignore
LICENSE
makefile
piping.script
README.md
src
test
test2
test4
testpipe
tests
lolipopping@debian$ls  >test4
lolipopping@debian$cat<test3
open 1: No such file or directory
]0;lolipopping@debian: ~/Documents/rshelllolipopping@debian:~/Documents/rshell$ c[Kbin/rshe[Kell
lolipopping@debian$cat<test4
bin
LICENSE
makefile
piping.script
README.md
src
test
test2
test4
test5
testpipe
tests
lolipopping@debian$ls>test    >test4
lolipopping@debian$cat<test4
bin
LICENSE
makefile
piping.script
README.md
src
test
test2
test4
test5
testpipe
tests
bin
LICENSE
makefile
piping.script
README.md
src
test
test2
test4
test5
testpipe
tests
lolipopping@debian$ls
bin	 makefile	README.md  test   test4  testpipe
LICENSE  piping.script	src	   test2  test5  tests
lolipopping@debian$rm test test4 test2 test5
lolipopping@debian$#piping
lolipopping@debian$ls | grep e
makefile
testpipe
tests
lolipopping@debian$ls | grep e | grep p
testpipe
lolipopping@debian$cat | ac  cat | cat
asdf
asdf
asdf
asdf
asdf
asdf
asdf
asdf
do
do
^C
]0;lolipopping@debian: ~/Documents/rshelllolipopping@debian:~/Documents/rshell$ bin/rshell
lolipopping@debian$ls \ grep        | grep e
makefile
testpipe
tests
lolipopping@debian$cat|cat|cat|cat
adsf
adsf
hi
hi
^C
]0;lolipopping@debian: ~/Documents/rshelllolipopping@debian:~/Documents/rshell$ bin/rshell
lolipopping@debian$ls | grep e > test9
lolipopping@debian$cat<test9
makefile
test9
testpipe
tests
lolipopping@debian$cat<test9|grep e
makefile
test9
testpipe
tests
lolipopping@debian$cat     <      test  9      |           get  te  rep e | cat
makefile
test9
testpipe
tests
lolipopping@debian$clear
[3;J[H[2Jlolipopping@debian$#extra credit
lolipopping@debian$cat<<<      <<< "hello:"
hello:
lolipopping@debian$cat <<< hi ; cat <<< hi
hi
hi
lolipopping@debian$cat <<< "extra credit rocks"
extra credit rocks
lolipopping@debian$cat <<< hi || cat <<< hi
hi
lolipopping@debian$exit
]0;lolipopping@debian: ~/Documents/rshelllolipopping@debian:~/Documents/rshell$ eexi[K[K[Kxit
exit

Script done on Wed 13 May 2015 09:28:29 PM PDT
